<html>
<head>
<title>appLista REST API</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
<div class="well">
<h1>appLista REST API</h1>
</div>
<div class="container">
<div class="row">

<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Produto</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/produto/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/produto/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/produto/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/produto/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/produto/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/produto/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/produto/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/produto/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Usuario_Nivel_Acesso</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/usuario_nivel_acesso/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/usuario_nivel_acesso/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/usuario_nivel_acesso/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/usuario_nivel_acesso/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/usuario_nivel_acesso/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/usuario_nivel_acesso/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/usuario_nivel_acesso/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/usuario_nivel_acesso/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Status</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/status/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/status/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/status/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/status/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/status/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/status/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/status/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/status/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Categorias</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/categorias/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/categorias/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/categorias/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/categorias/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/categorias/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/categorias/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/categorias/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/categorias/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Itens_Pedido</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/itens_pedido/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/itens_pedido/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/itens_pedido/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/itens_pedido/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/itens_pedido/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/itens_pedido/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/itens_pedido/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/itens_pedido/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Marca</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/marca/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/marca/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/marca/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/marca/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/marca/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/marca/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/marca/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/marca/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Unidade_Medida</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/unidade_medida/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/unidade_medida/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/unidade_medida/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/unidade_medida/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/unidade_medida/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/unidade_medida/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/unidade_medida/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/unidade_medida/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Pedido</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/pedido/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/pedido/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/pedido/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/pedido/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/pedido/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/pedido/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/pedido/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/pedido/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Usuario_Tipo</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/usuario_tipo/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/usuario_tipo/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/usuario_tipo/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/usuario_tipo/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/usuario_tipo/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/usuario_tipo/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/usuario_tipo/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/usuario_tipo/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Loja</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/loja/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/loja/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/loja/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/loja/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/loja/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/loja/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/loja/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/loja/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Usuarios</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/usuarios/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/usuarios/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/usuarios/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/usuarios/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/usuarios/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/usuarios/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/usuarios/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/usuarios/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Usuario_Status</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/usuario_status/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/usuario_status/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/usuario_status/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/usuario_status/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/usuario_status/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/usuario_status/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/usuario_status/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/usuario_status/delete.php</td></tr></tbody></table>

</div>
</div>

</body>
</html>
