<html>
<head>
<title>apiCondominios REST API</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
</head>
<body>
<div class="well">
<h1>apiCondominios REST API</h1>
</div>
<div class="container">
<div class="row">

<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Nivel_Acessos</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/nivel_acessos/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/nivel_acessos/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/nivel_acessos/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/nivel_acessos/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/nivel_acessos/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/nivel_acessos/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/nivel_acessos/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/nivel_acessos/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Visitantes</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/visitantes/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/visitantes/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/visitantes/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/visitantes/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/visitantes/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/visitantes/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/visitantes/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/visitantes/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Users</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/users/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/users/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/users/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/users/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/users/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/users/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/users/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/users/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Ocorrencias</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/ocorrencias/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/ocorrencias/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/ocorrencias/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/ocorrencias/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/ocorrencias/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/ocorrencias/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/ocorrencias/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/ocorrencias/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Enquete_Votos</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/enquete_votos/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/enquete_votos/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/enquete_votos/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/enquete_votos/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/enquete_votos/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/enquete_votos/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/enquete_votos/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/enquete_votos/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Boletos</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/boletos/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/boletos/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/boletos/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/boletos/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/boletos/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/boletos/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/boletos/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/boletos/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Enquetes</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/enquetes/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/enquetes/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/enquetes/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/enquetes/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/enquetes/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/enquetes/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/enquetes/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/enquetes/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Achados_Perdidos</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/achados_perdidos/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/achados_perdidos/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/achados_perdidos/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/achados_perdidos/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/achados_perdidos/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/achados_perdidos/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/achados_perdidos/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/achados_perdidos/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Veiculos</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/veiculos/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/veiculos/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/veiculos/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/veiculos/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/veiculos/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/veiculos/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/veiculos/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/veiculos/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Pets</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/pets/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/pets/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/pets/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/pets/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/pets/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/pets/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/pets/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/pets/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Murallikes</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/murallikes/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/murallikes/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/murallikes/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/murallikes/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/murallikes/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/murallikes/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/murallikes/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/murallikes/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Areas</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/areas/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/areas/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/areas/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/areas/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/areas/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/areas/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/areas/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/areas/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Condominios</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/condominios/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/condominios/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/condominios/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/condominios/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/condominios/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/condominios/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/condominios/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/condominios/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Unidades</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/unidades/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/unidades/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/unidades/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/unidades/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/unidades/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/unidades/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/unidades/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/unidades/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Migrations</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/migrations/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/migrations/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/migrations/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/migrations/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/migrations/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/migrations/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/migrations/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/migrations/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Convidados</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/convidados/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/convidados/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/convidados/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/convidados/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/convidados/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/convidados/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/convidados/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/convidados/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Planos</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/planos/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/planos/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/planos/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/planos/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/planos/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/planos/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/planos/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/planos/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Moradores</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/moradores/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/moradores/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/moradores/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/moradores/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/moradores/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/moradores/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/moradores/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/moradores/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Classificados</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/classificados/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/classificados/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/classificados/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/classificados/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/classificados/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/classificados/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/classificados/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/classificados/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Reservas</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/reservas/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/reservas/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/reservas/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/reservas/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/reservas/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/reservas/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/reservas/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/reservas/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Murals</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/murals/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/murals/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/murals/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/murals/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/murals/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/murals/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/murals/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/murals/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Documentos</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/documentos/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/documentos/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/documentos/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/documentos/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/documentos/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/documentos/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/documentos/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/documentos/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Personal_Access_Tokens</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/personal_access_tokens/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/personal_access_tokens/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/personal_access_tokens/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/personal_access_tokens/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/personal_access_tokens/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/personal_access_tokens/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/personal_access_tokens/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/personal_access_tokens/delete.php</td></tr></tbody></table>
<table class='table table-striped table-condensed'> <thead> <tr><th colspan='3'><div class='p-3 mb-2 bg-primary text-white'><h3><b>Area_Dias_Indisponiveis</b></h3></div><tr></th></thead><tbody><tr><td>Read</td><td>GET</td><td>/area_dias_indisponiveis/read.php?pageno=1&pagesize=30</td></tr><tr><td>Read One</td><td>GET</td><td>/area_dias_indisponiveis/read_one.php?id=1</td></tr><tr><td>Search</td><td>GET</td><td>/area_dias_indisponiveis/search.php?key=key&pageno=1&pagesize=30</td></tr><tr><td>Dynamic Search</td><td>POST</td><td>/area_dias_indisponiveis/search_by_column.php</td></tr><tr><td>Create</td><td>POST</td><td>/area_dias_indisponiveis/create.php</td></tr><tr><td>Update</td><td>POST</td><td>/area_dias_indisponiveis/update.php</td></tr><tr><td>Update Patch</td><td>POST</td><td>/area_dias_indisponiveis/update_patch.php</td></tr><tr><td>Delete</td><td>POST</td><td>/area_dias_indisponiveis/delete.php</td></tr></tbody></table>

</div>
</div>

</body>
</html>
